<a href="https://colab.research.google.com/github/Venkatesh-80/Machine-Learning-Foundation/blob/main/Copy_of_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np


In [ ]:
import numpy as np
cost_price = np.array([1500,3000,5000])

In [ ]:
print(cost_price.shape)
print(cost_price.ndim)

(3,)
1


In [ ]:
daily_sales = np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])

In [ ]:
print(daily_sales.shape)
print(daily_sales.ndim)


(3, 4)
2


In [ ]:
result = daily_sales+2
print(result)
print(np.sum(result,axis=0))

[[12 17 10 14]
 [ 7  9  6  8]
 [ 4  5  4  6]]
[23 31 20 28]


In [ ]:
result = np.dot(cost_price,daily_sales)
print(result)
print(np.sqrt(daily_sales))


[40000 58500 34000 56000]
[[3.16227766 3.87298335 2.82842712 3.46410162]
 [2.23606798 2.64575131 2.         2.44948974]
 [1.41421356 1.73205081 1.41421356 2.        ]]


In [ ]:
print(daily_sales[1])

[5 7 4 6]


In [ ]:
print(daily_sales[:,0:2])

[[10 15]
 [ 5  7]
 [ 2  3]]


In [ ]:
print(daily_sales.reshape(1,12))

[[10 15  8 12  5  7  4  6  2  3  2  4]]


In [ ]:
print(daily_sales.reshape(2,6))

[[10 15  8 12  5  7]
 [ 4  6  2  3  2  4]]


In [ ]:
predict_sales = np.random.randint(daily_sales.min(),daily_sales.max(),size=(3,4))  #daily_sales = np.array([[10,15,8,12],[5,7,4,6],[2,3,2,4]])
print(predict_sales)

[[10  8  6 14]
 [ 8 14 12  3]
 [11  2 10  4]]


In [ ]:
print(np.random.rand(5))

[0.48099149 0.97588556 0.21634416 0.67479677 0.39637309]


In [ ]:
print(np.sum(predict_sales))
print(np.sum(predict_sales,axis=0))
print(np.sum(predict_sales,axis=1))

102
[29 24 28 21]
[38 37 27]


In [ ]:
marks = np.array([[78,85,90],[45,60,55],[88,90,95],[30,40,45],[65,70,75]])
print(marks)

[[78 85 90]
 [45 60 55]
 [88 90 95]
 [30 40 45]
 [65 70 75]]


In [ ]:
print(marks.shape)
print(marks.size)
print(marks.ndim)
print(marks.dtype)

(5, 3)
15
2
int64


In [ ]:
print(marks[1:2])

[[45 60 55]]


In [ ]:
print(marks[:,2])

[90 55 95 45 75]


In [ ]:
print(marks[0,1])

85


In [ ]:
print(np.mean(marks,axis =0))
print(np.mean(marks,axis =1))


[61.2 69.  72. ]
[84.33333333 53.33333333 91.         38.33333333 70.        ]


In [ ]:
print(marks>=80)

[[False  True  True]
 [False False False]
 [ True  True  True]
 [False False False]
 [False False False]]


In [ ]:
marks +=5
print(marks)

[[ 83  90  95]
 [ 50  65  60]
 [ 93  95 100]
 [ 35  45  50]
 [ 70  75  80]]


In [ ]:
mark = np.where(marks>=50,"1","0")
print(mark)

[['1' '1' '1']
 ['1' '1' '1']
 ['1' '1' '1']
 ['0' '0' '1']
 ['1' '1' '1']]


In [ ]:
mark = np.where(marks<=40,0,marks)
print(mark)

[[ 83  90  95]
 [ 50  65  60]
 [ 93  95 100]
 [  0  45  50]
 [ 70  75  80]]


In [ ]:
avg = np.mean(marks,axis=1)
print(avg)

[89.33333333 58.33333333 96.         43.33333333 75.        ]


In [ ]:
Grades = np.where(avg>=85,'A',np.where(avg>=70,'B',np.where(avg>=50,'C','0')))
print(Grades)

['A' 'C' 'A' '0' 'B']


In [ ]:
backup = marks.copy()
marks[0,0]=0
print(backup)
print(marks)

[[ 83  90  95]
 [ 50  65  60]
 [ 93  95 100]
 [ 35  45  50]
 [ 70  75  80]]
[[  0  90  95]
 [ 50  65  60]
 [ 93  95 100]
 [ 35  45  50]
 [ 70  75  80]]


In [ ]:
electricity = np.random.randint(120,650,size=(4,7))
print(electricity)
print(electricity.shape)
print(electricity.size)
print(electricity.ndim)
print(electricity.dtype)

[[371 311 258 210 334 328 416]
 [192 482 164 428 581 219 533]
 [570 564 423 443 610 349 454]
 [288 500 468 200 636 320 531]]
(4, 7)
28
2
int64


In [ ]:
import numpy as np
electricity = np.random.randint(120,650,size=(4,7))
print(electricity)
print(electricity.shape)
print(electricity.size)
print(electricity.ndim)
print(electricity.dtype)
average_usage_per_hostel = np.mean(electricity, axis=1)
print("Average electricity usage per hostel:")
print(average_usage_per_hostel)

[[207 575 642 190 128 303 429]
 [611 348 272 418 505 274 636]
 [335 417 645 300 473 542 151]
 [268 230 273 470 244 186 321]]
(4, 7)
28
2
int64
Average electricity usage per hostel:
[353.42857143 437.71428571 409.         284.57142857]


In [ ]:
maximum_usage_per_hostel = np.max(electricity, axis=1)
print("Maximum electricity usage per hostel:")
print(maximum_usage_per_hostel)

Maximum electricity usage per hostel:
[642 636 645 470]


In [ ]:
highest_avg_usage_hostel_index = np.argmax(average_usage_per_hostel)
highest_avg_usage_hostel_number = highest_avg_usage_hostel_index + 1
highest_avg_usage_value = average_usage_per_hostel[highest_avg_usage_hostel_index]

print(f"Hostel with the highest average electricity usage: Hostel {highest_avg_usage_hostel_number}")
print(f"Average usage for this hostel: {highest_avg_usage_value:.2f}")

Hostel with the highest average electricity usage: Hostel 2
Average usage for this hostel: 437.71


In [ ]:
print(np.where(electricity>550,electricity*1.20,electricity))


[[207.  690.  770.4 190.  128.  303.  429. ]
 [733.2 348.  272.  418.  505.  274.  763.2]
 [335.  417.  774.  300.  473.  542.  151. ]
 [268.  230.  273.  470.  244.  186.  321. ]]


In [ ]:
week_avg=electricity.mean(axis=0)
above_avg=electricity>week_avg
print(above_avg)

[[False  True  True False False False  True]
 [ True False False  True  True False  True]
 [False  True  True False  True  True False]
 [False False False  True False False False]]


In [ ]:
import numpy as np
import pandas as pd


In [ ]:
s=pd.Series([10, 20, 30, 40, 50])
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64


In [ ]:
s=pd.Series([10,20,30],index=["a","b","c"])
print(s)

a    10
b    20
c    30
dtype: int64


In [ ]:
print(s["a"])

10


In [ ]:
print(s[0])

10


/tmp/ipython-input-287792665.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  print(s[0])


In [ ]:
data={"Math":90,"Physics":85,"Chemistry":88}

In [ ]:
marks=pd.Series(data)

In [ ]:
print(data)

{'Math': 90, 'Physics': 85, 'Chemistry': 88}


In [ ]:
print(marks)

Math         90
Physics      85
Chemistry    88
dtype: int64


Data Frames in **Pandas**

In [ ]:
data={
    "Name": ["Aman","Krish","Karan"],
    "Age": [22,23,21],
    "Marks": [85,90,88]
}
print(data)



{'Name': ['Aman', 'Krish', 'Karan'], 'Age': [22, 23, 21], 'Marks': [85, 90, 88]}


In [ ]:
type(data)

dict

In [ ]:
marks=pd.DataFrame(data)
print(marks)

    Name  Age  Marks
0   Aman   22     85
1  Krish   23     90
2  Karan   21     88


In [ ]:
marks=pd.DataFrame(
    data,
    index=["Student1","Student2","Student3"]
)

In [ ]:
print(marks)

           Name  Age  Marks
Student1   Aman   22     85
Student2  Krish   23     90
Student3  Karan   21     88


In [ ]:
marks.set_index("Name",inplace=True)   #If you are setting inplace = true it means you are changing the original object itself.

In [ ]:
df=pd.DataFrame({
    "Name": ["Aman","Krish","Karan","venky","Raj","Hari","Kumar","Krishna"],
    "Age": [22,23,21,23,45,67,23,25],
    "Marks": [85,90,88,90,99,100,67,89]
})
print(df)

      Name  Age  Marks
0     Aman   22     85
1    Krish   23     90
2    Karan   21     88
3    venky   23     90
4      Raj   45     99
5     Hari   67    100
6    Kumar   23     67
7  Krishna   25     89


#head prints first 5 rows and tail prints last 5 rows if data is less than 5 then output for both head and tail will be same

In [ ]:
df.head()

,Name,Age,Marks
0,Aman,22,85
1,Krish,23,90
2,Karan,21,88
3,venky,23,90
4,Raj,45,99


In [ ]:
df.tail()

,Name,Age,Marks
3,venky,23,90
4,Raj,45,99
5,Hari,67,100
6,Kumar,23,67
7,Krishna,25,89


In [ ]:
df.head(2)

,Name,Age,Marks
0,Aman,22,85
1,Krish,23,90


In [ ]:
df.tail(2)

,Name,Age,Marks
6,Kumar,23,67
7,Krishna,25,89


In [ ]:
df.shape

(8, 3)

In [ ]:
df.columns

Index(['Name', 'Age', 'Marks'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   Name    8 non-null      object
 1   Age     8 non-null      int64 
 2   Marks   8 non-null      int64 
dtypes: int64(2), object(1)
memory usage: 324.0+ bytes


In [ ]:
df.describe()

,Age,Marks
count,8.000000,8.000000
mean,31.125000,88.500000
std,16.478883,10.155927
min,21.000000,67.000000
25%,22.750000,87.250000
50%,23.000000,89.500000
75%,30.000000,92.250000
max,67.000000,100.000000


**Selecting The Data**

In [ ]:
df["Name"]

,Name
0,Aman
1,Krish
2,Karan
3,venky
4,Raj
5,Hari
6,Kumar
7,Krishna


In [ ]:
df[["Name","Marks"]]

,Name,Marks
0,Aman,85
1,Krish,90
2,Karan,88
3,venky,90
4,Raj,99
5,Hari,100
6,Kumar,67
7,Krishna,89


**Filtering in Pandas**

In [ ]:
df[df["Marks"]>85]

,Name,Age,Marks
1,Krish,23,90
2,Karan,21,88
3,venky,23,90
4,Raj,45,99
5,Hari,67,100
7,Krishna,25,89


Handling Missing Values


In [ ]:
df=pd.DataFrame({
    "Name": ["Aman","Krish","Karan",None,"venky","Ram"],
    "Age":  [22,23,None,22,25,26],
    "Marks": [85,None,88,90,56,None]
})

df

,Name,Age,Marks
0,Aman,22.0,85.0
1,Krish,23.0,NaN
2,Karan,NaN,88.0
3,None,22.0,90.0
4,venky,25.0,56.0
5,Ram,26.0,NaN


In [ ]:
df.isnull()  #Checking the missing values

,Name,Age,Marks
0,False,False,False
1,False,False,True
2,False,True,False
3,True,False,False
4,False,False,False
5,False,False,True


In [ ]:
df.isnull().sum()     #count the missing values

,0
Name,1
Age,1
Marks,2


In [ ]:
df.dropna()

,Name,Age,Marks
0,Aman,22.0,85.0
4,venky,25.0,56.0


In [ ]:
print(df)

    Name   Age  Marks
0   Aman  22.0   85.0
1  Krish  23.0    NaN
2  Karan   NaN   88.0
3   None  22.0   90.0
4  venky  25.0   56.0
5    Ram  26.0    NaN


In [ ]:
cleaned_data=df.dropna()
print(cleaned_data)

    Name   Age  Marks
0   Aman  22.0   85.0
4  venky  25.0   56.0


**`Pandas`**  Exercise




In [ ]:
data=pd.DataFrame({
    "Name": ["Aman","Saurav","Karan","Shubham","Abhishek",None,"Sameer"],
    "Age":  [22,23,None,22,25,24,26],
    "Marks": [85,None,88,90,56,72,None],
    "Subject": ["Math","Physics","Math","Chemistry","Math","Physics","Chemistry"]
})
print(data)

       Name   Age  Marks    Subject
0      Aman  22.0   85.0       Math
1    Saurav  23.0    NaN    Physics
2     Karan   NaN   88.0       Math
3   Shubham  22.0   90.0  Chemistry
4  Abhishek  25.0   56.0       Math
5      None  24.0   72.0    Physics
6    Sameer  26.0    NaN  Chemistry


In [ ]:
print(data.shape)
print(data.dtypes)

(7, 4)
Name        object
Age        float64
Marks      float64
Subject     object
dtype: object


In [ ]:
df[["Name","Marks"]]

,Name,Marks
0,Aman,85.0
1,Krish,NaN
2,Karan,88.0
3,None,90.0
4,venky,56.0
5,Ram,NaN


In [ ]:
data.sort_values(by="Marks",ascending=False)

,Name,Age,Marks,Subject
3,Shubham,22.0,90.0,Chemistry
2,Karan,NaN,88.0,Math
0,Aman,22.0,85.0,Math
5,None,24.0,72.0,Physics
4,Abhishek,25.0,56.0,Math
1,Saurav,23.0,NaN,Physics
6,Sameer,26.0,NaN,Chemistry


In [ ]:
print(data.isnull().sum())


Name       1
Age        1
Marks      2
Subject    0
dtype: int64
